using System;
using System.Collections.Generic;
using System.Text;

namespace WzComparerR2.CharaSim
{
    public enum ItemPropType
    {
        price = 1,
        lv,
        reqLevel,
        cash,
        quest,
        pquest,
        tradeBlock,
        notSale,
        only,
        tradeAvailable,
        accountSharable,
        exchangeableOnce,
        timeLimited,
        setItemID,
        charismaEXP,
        senseEXP,
        insightEXP,
        willEXP,
        craftEXP,
        charmEXP,
        nickTag,
        wonderGrade,
        life,
        permanent,
        multiPet,
        limitedLife,
        flatRate,
        noMoveToLocker,
        exp_minLev,
        exp_maxLev,
        dressUpgrade,
        onlyCash,
        noScroll,
        noRevive,
        pickupItem,
        longRange,
        sweepForDrop,
        pickupAll,
        consumeHP,
        consumeMP,
        autoBuff,
        giantPet,
        consumeCure,
        useTradeBlock,
        level,
        sharableOnce,
        BTSLabel,
        BLACKPINKLabel,
        addTooltip_tuc,
        addTooltip_tucCnt,
        pointCost,
        tamingMob,
    }
}
